services:
  backend:
    container_name: kimfe-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    entrypoint: sh -c "chmod +x /app/run.sh && chmod +x /app/llama-run.sh && /app/run.sh"

  frontend:
    container_name: kimfe-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: deps  # Especificamos que use la etapa de desarrollo
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped