version: '3.8'

services:

  backend-plane-conf:
    container_name: kimfe-backend-plane-conf
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/app/

    entrypoint: python /app/run_core.py
    # Path: backend
    # backend/llama-run.sh -f deploy.py 

  backend-deploys:
    
    container_name: kimfe-backend-deploys
    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./backend/:/app/

    entrypoint: python /app/deploy.py
    depends_on:
      - backend-plane-conf
    restart: on-failure:5s

  frontend:

    container_name: kimfe-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/app/src
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000