import DOMInspector from "../components/DomInspector";
import AnalyticsTracker from "../components/AnalyticsTracker";
import Branding from "../components/Branding";
import ErrorBoundaryClient from "../components/ErrorBoundaryClient";
import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body><DOMInspector><ErrorBoundaryClient>{children}<Branding /></ErrorBoundaryClient><AnalyticsTracker siteKey="67cf7e7836e49ff1651a2e03" /></DOMInspector></body>
    </html>
  );
}

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
